version: '3.9'

services:
  db:
    container_name: parser_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=parsers
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432